// ComplaintPage.jsx — AI Complaint/FIR Draft Generator
import { useState } from 'react';
import { FileText, Loader2, Download, Copy, CheckCircle, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';
import { generateComplaint } from '../utils/api';
import PageHeader from '../components/PageHeader';

const G = '#c9a84c';
const MUTED = '#5c5870';

const LABEL = ({ children, required }) => (
  <div style={{ fontSize: 10, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.09em', color: G, marginBottom: 7 }}>
    {children}{required && <span style={{ color: '#e05252', marginLeft: 3 }}>*</span>}
  </div>
);

const Field = ({ label, required, children }) => (
  <div>
    <LABEL required={required}>{label}</LABEL>
    {children}
  </div>
);

export default function ComplaintPage() {
  const [form, setForm] = useState({
    situation: '', complainantName: '', respondentName: '',
    place: '', date: '', witnesses: '',
  });
  const [result, setResult]   = useState(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied]   = useState(false);

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));

  const handleGenerate = async () => {
    if (form.situation.trim().length < 20) {
      toast.error('Please describe the situation in more detail.');
      return;
    }
    setLoading(true);
    try {
      const data = await generateComplaint(form);
      setResult(data);
      if (data.isDistress) toast.error('⚠️ Emergency detected — Police: 100 · Women: 1091 · Emergency: 112', { duration: 7000 });
      else toast.success('Complaint draft ready!');
    } catch (err) {
      toast.error(err?.response?.data?.error || 'Failed to generate. Check backend connection.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(result.draft);
    setCopied(true);
    toast.success('Copied to clipboard!');
    setTimeout(() => setCopied(false), 2200);
  };

  const handleDownload = () => {
    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>NyayaBot Complaint / FIR Draft</title>
<style>
  body { font-family: 'Times New Roman', serif; font-size: 13pt; line-height: 1.8; max-width: 700px; margin: 40px auto; padding: 0 30px; color: #000; }
  pre { font-family: inherit; white-space: pre-wrap; word-wrap: break-word; }
  .footer { margin-top: 40px; font-size: 10pt; color: #555; text-align: center; border-top: 1px solid #ccc; padding-top: 10px; }
  @media print { body { margin: 20px; } }
</style>
</head>
<body>
<pre>${result.draft}</pre>
<div class="footer">Generated by NyayaBot — AI Legal Companion for India | Not a substitute for legal advice</div>
</body>
</html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url  = URL.createObjectURL(blob);
    const win  = window.open(url, '_blank');
    if (win) {
      win.addEventListener('load', () => { setTimeout(() => { win.print(); URL.revokeObjectURL(url); }, 500); });
    }
    toast.success('Opening PDF for download...');
  };

  return (
    <div>
      <PageHeader icon="📄" title="Complaint / FIR Generator" subtitle="AI drafts a legally formatted police complaint with correct IPC/BNS sections" />

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, alignItems: 'start' }}>

        {/* ── LEFT: Form ── */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>

          {/* Situation box */}
          <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '16px 18px' }}>
            <Field label="Situation / What Happened" required>
              <textarea
                value={form.situation}
                onChange={e => set('situation', e.target.value)}
                placeholder="Describe exactly what happened — when, where, who was involved, what occurred..."
                className="input-field"
                style={{ minHeight: 130, resize: 'vertical', lineHeight: 1.65 }}
              />
            </Field>
          </div>

          {/* Name row */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '14px 16px' }}>
              <Field label="Your Name (Optional)">
                <input value={form.complainantName} onChange={e => set('complainantName', e.target.value)} placeholder="Your full name" className="input-field" />
              </Field>
            </div>
            <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '14px 16px' }}>
              <Field label="Accused Name (Optional)">
                <input value={form.respondentName} onChange={e => set('respondentName', e.target.value)} placeholder="Accused / respondent name" className="input-field" />
              </Field>
            </div>
          </div>

          {/* Place + Date row */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '14px 16px' }}>
              <Field label="Place of Incident">
                <input value={form.place} onChange={e => set('place', e.target.value)} placeholder="Village / Street / City" className="input-field" />
              </Field>
            </div>
            <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '14px 16px' }}>
              <Field label="Date of Incident">
                <input type="date" value={form.date} onChange={e => set('date', e.target.value)} className="input-field" style={{ colorScheme: 'dark' }} />
              </Field>
            </div>
          </div>

          {/* Witnesses */}
          <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '14px 16px' }}>
            <Field label="Witnesses (Optional)">
              <input value={form.witnesses} onChange={e => set('witnesses', e.target.value)} placeholder="Names and contact of witnesses" className="input-field" />
            </Field>
          </div>

          {/* Generate button */}
          <button
            onClick={handleGenerate}
            disabled={loading || form.situation.trim().length < 5}
            className="btn-primary"
            style={{ width: '100%', justifyContent: 'center', padding: '12px', fontSize: 14 }}
          >
            {loading ? <Loader2 size={16} style={{ animation: 'spin 0.8s linear infinite' }} /> : <FileText size={16} />}
            {loading ? 'Generating Draft...' : 'Generate Complaint Draft'}
          </button>

          {/* Filing guide */}
          {result?.filingGuide && (
            <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '16px 18px', animation: 'fadeIn 0.3s ease' }}>
              <div style={{ fontSize: 10, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.09em', color: MUTED, marginBottom: 12 }}>How to File FIR</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {result.filingGuide.map((step, i) => (
                  <div key={i} style={{ display: 'flex', gap: 11, alignItems: 'flex-start' }}>
                    <div style={{ width: 22, height: 22, borderRadius: '50%', background: 'linear-gradient(135deg,#c9a84c,#f0d080)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10, fontWeight: 800, color: '#09080a', flexShrink: 0, marginTop: 1 }}>{step.step}</div>
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 600, color: '#e8e3d5', lineHeight: 1.3 }}>{step.title}</div>
                      <div style={{ fontSize: 11.5, color: MUTED, marginTop: 2, lineHeight: 1.5 }}>{step.description}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* ── RIGHT: Result ── */}
        <div>
          {/* Loading state */}
          {loading && (
            <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '52px 24px', textAlign: 'center', animation: 'fadeIn 0.25s ease' }}>
              <div style={{ width: 40, height: 40, border: '2px solid rgba(201,168,76,0.15)', borderTop: `2px solid ${G}`, borderRadius: '50%', animation: 'spin 0.8s linear infinite', margin: '0 auto 16px' }} />
              <div style={{ fontSize: 13, color: MUTED }}>Drafting your complaint with IPC/BNS sections...</div>
            </div>
          )}

          {/* Result */}
          {result?.draft && !loading && (
            <div style={{ background: '#111122', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 13, padding: '18px 20px', animation: 'fadeIn 0.3s ease' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
                <div style={{ fontSize: 10, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.09em', color: MUTED }}>Generated Draft</div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button onClick={handleCopy} className="btn-ghost">
                    {copied ? <CheckCircle size={12} color="#3dba7a" /> : <Copy size={12} />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                  <button onClick={handleDownload} className="btn-ghost">
                    <Download size={12} /> Download
                  </button>
                </div>
              </div>

              {result.isDistress && (
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '9px 12px', borderRadius: 9, marginBottom: 12, background: 'rgba(224,82,82,0.09)', border: '1px solid rgba(224,82,82,0.22)', color: '#e05252', fontSize: 12 }}>
                  <AlertTriangle size={13} /> Emergency detected — Police: 100 · Women: 1091 · Emergency: 112
                </div>
              )}

              <div style={{
                fontFamily: 'JetBrains Mono, monospace', fontSize: 12, lineHeight: 1.75,
                color: 'rgba(232,227,213,0.80)', whiteSpace: 'pre-wrap',
                background: '#09090f', border: '1px solid rgba(255,255,255,0.06)',
                borderRadius: 10, padding: '16px 18px', maxHeight: 520, overflowY: 'auto',
              }}>
                {result.draft}
              </div>

              <div style={{ fontSize: 11, color: 'rgba(92,88,112,0.70)', marginTop: 12, textAlign: 'center', lineHeight: 1.5 }}>
                ⚠️ AI-generated draft — review carefully and consult a lawyer before filing
              </div>
            </div>
          )}

          {/* Empty state */}
          {!result && !loading && (
            <div style={{
              background: '#111122', border: '1px solid rgba(255,255,255,0.07)',
              borderRadius: 13, padding: '60px 28px', textAlign: 'center',
            }}>
              <div style={{ width: 56, height: 56, background: 'rgba(201,168,76,0.09)', border: '1px solid rgba(201,168,76,0.18)', borderRadius: 16, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 26, margin: '0 auto 16px' }}>📄</div>
              <div style={{ fontSize: 14, fontWeight: 500, color: '#e8e3d5', marginBottom: 6 }}>Complaint Draft</div>
              <div style={{ fontSize: 12.5, color: MUTED, lineHeight: 1.65, maxWidth: 260, margin: '0 auto 8px' }}>Fill in the form and click Generate to create a legally formatted draft</div>
              <div style={{ fontSize: 11, color: 'rgba(92,88,112,0.60)' }}>IPC / BNS sections added automatically</div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
