// RTIPage.jsx - RTI Application Generator with PDF Download + FIR Digitalization
import { useState } from 'react';
import { FileQuestion, Loader2, Copy, CheckCircle, Download, FileText } from 'lucide-react';
import toast from 'react-hot-toast';
import PageHeader from '../components/PageHeader';

const G = '#c9a84c', GL = '#f0d080', TEXT = '#e8e4d8', MUTED = '#6b6880';

const RTI_GUIDE_STEPS = [
  { step: 1, title: 'Write the Application', description: 'Write on plain A4 paper or type it. Address to the Public Information Officer (PIO) of the concerned department. No specific format is required.' },
  { step: 2, title: 'Pay the Fee', description: 'Pay ₹10 as application fee via Indian Postal Order (IPO), Demand Draft, or cash (in some offices). BPL card holders are exempt from fee.' },
  { step: 3, title: 'Submit the Application', description: 'Submit physically to the PIO or send by post (registered). You can also file online at rtionline.gov.in for Central Government departments.' },
  { step: 4, title: 'Receive Acknowledgement', description: 'PIO must acknowledge receipt. Keep this acknowledgement safely as proof of submission.' },
  { step: 5, title: 'Wait for Response', description: 'PIO must respond within 30 days. For matters related to life/liberty, the deadline is 48 hours.' },
  { step: 6, title: 'File First Appeal if Needed', description: 'If unsatisfied or no response within 30 days, file a first appeal before the First Appellate Authority within 30 days of the deadline.' },
];

const RTI_EXEMPTIONS = [
  'Information that would harm national security or intelligence operations',
  'Cabinet papers and deliberations of Council of Ministers',
  'Information received in confidence from a foreign government',
  'Information which would endanger the life or safety of any person',
  'Personal information with no public activity or interest justification',
  'Trade secrets or intellectual property that would harm competitive position',
];

const INPUT_STYLE = {
  width: '100%',
  background: '#0d0d1a',
  border: '1px solid rgba(255,255,255,0.1)',
  borderRadius: 10,
  color: TEXT,
  fontFamily: 'DM Sans,sans-serif',
  fontSize: 14,
  padding: '12px 14px',
  outline: 'none',
  marginBottom: 0,
  boxSizing: 'border-box',
};

const LABEL_STYLE = {
  display: 'block',
  fontSize: 11,
  color: '#c9a84c',
  fontFamily: 'JetBrains Mono,monospace',
  letterSpacing: 1,
  textTransform: 'uppercase',
  marginBottom: 6,
  fontWeight: 600,
};

async function generateRTIWithAI(form) {
  const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
  const res = await fetch(`${API_URL}/api/rti/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(form),
  });
  if (!res.ok) throw new Error(`Server error: ${res.status}`);
  const data = await res.json();
  return data.application || data.result || data.draft || '';
}

function downloadPDF(text, filename, title) {
  // Generate a clean HTML page and print to PDF
  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  body { font-family: 'Times New Roman', Times, serif; font-size: 13pt; line-height: 1.8; color: #000; max-width: 700px; margin: 40px auto; padding: 0 30px; }
  h1 { font-size: 16pt; text-align: center; text-decoration: underline; margin-bottom: 20px; }
  pre { font-family: inherit; white-space: pre-wrap; word-wrap: break-word; }
  .footer { margin-top: 40px; font-size: 10pt; color: #555; text-align: center; border-top: 1px solid #ccc; padding-top: 10px; }
  @media print { body { margin: 20px; } }
</style>
</head>
<body>
<pre>${text}</pre>
<div class="footer">Generated by NyayaBot — AI Legal Companion for India · Not a substitute for legal advice</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  if (win) {
    win.addEventListener('load', () => {
      setTimeout(() => { win.print(); URL.revokeObjectURL(url); }, 500);
    });
  }
}

export default function RTIPage() {
  const [form, setForm] = useState({ subject: '', department: '', specificInfo: '', applicantName: '', applicantAddress: '' });
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState('generate');

  const DEPARTMENTS = ['Municipal Corporation', 'Police Department', 'RTO / Transport', 'Public Works Department', 'Revenue Department', 'Education Department', 'Health Department', 'Income Tax Department'];

  const handleGenerate = async () => {
    if (!form.subject.trim() || !form.specificInfo.trim()) {
      toast.error('Please fill in the subject and specific information needed');
      return;
    }
    setLoading(true);
    try {
      const application = await generateRTIWithAI(form);
      setResult({ application, subject: form.subject });
      toast.success('RTI Application generated!');
    } catch (err) {
      toast.error('Generation failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result.application);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast.success('RTI Application copied!');
  };

  const handleDownloadPDF = () => {
    downloadPDF(result.application, 'RTI_Application.pdf', 'RTI Application');
    toast.success('Opening PDF for download...');
  };

  const inp = (f, v) => setForm(prev => ({ ...prev, [f]: v }));

  return (
    <div>
      <PageHeader icon="📋" title="RTI Application Generator" subtitle="Auto-draft RTI application under RTI Act 2005 · AI-Powered · PDF Download" />

      {/* Tabs */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 24 }}>
        {[{ id: 'generate', label: '📝 Generate RTI' }, { id: 'guide', label: '📚 RTI Guide' }].map(tab => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)}
            style={{ flex: 1, padding: '10px 0', borderRadius: 11, fontSize: 13, fontWeight: 500, cursor: 'pointer', transition: 'all 0.15s', background: activeTab === tab.id ? G : '#111120', color: activeTab === tab.id ? '#0a0808' : MUTED, border: `1px solid ${activeTab === tab.id ? G : 'rgba(255,255,255,0.07)'}`, fontFamily: 'DM Sans,sans-serif' }}>
            {tab.label}
          </button>
        ))}
      </div>

      {activeTab === 'generate' && (
        <div>
          {!result ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div style={{ background: '#111120', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 14, padding: 22 }}>
                <h3 style={{ fontFamily: 'Playfair Display,serif', fontSize: 16, color: G, marginBottom: 18 }}>Fill RTI Details</h3>

                <div style={{ marginBottom: 16 }}>
                  <label style={LABEL_STYLE}>Subject of RTI <span style={{ color: '#e85c5c' }}>*</span></label>
                  <input value={form.subject} onChange={e => inp('subject', e.target.value)}
                    placeholder="e.g., Status of my complaint filed on [date]" style={INPUT_STYLE} />
                </div>

                <div style={{ marginBottom: 16 }}>
                  <label style={LABEL_STYLE}>Department / Authority</label>
                  <input value={form.department} onChange={e => inp('department', e.target.value)}
                    placeholder="e.g., Municipal Corporation, Police Department, RTO..." style={INPUT_STYLE} />
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 8 }}>
                    {DEPARTMENTS.slice(0, 5).map(d => (
                      <button key={d} onClick={() => inp('department', d)}
                        style={{ fontSize: 11, padding: '3px 10px', borderRadius: 16, cursor: 'pointer', background: '#1a1a26', border: '1px solid rgba(42,42,62,1)', color: MUTED, transition: 'all 0.15s' }}
                        onMouseEnter={e => { e.currentTarget.style.color = G; e.currentTarget.style.borderColor = `${G}40`; }}
                        onMouseLeave={e => { e.currentTarget.style.color = MUTED; e.currentTarget.style.borderColor = 'rgba(42,42,62,1)'; }}>
                        {d}
                      </button>
                    ))}
                  </div>
                </div>

                <div style={{ marginBottom: 16 }}>
                  <label style={LABEL_STYLE}>Specific Information Needed <span style={{ color: '#e85c5c' }}>*</span></label>
                  <textarea value={form.specificInfo} onChange={e => inp('specificInfo', e.target.value)}
                    placeholder="List the specific information/documents you want, e.g.:&#10;1. Copy of my FIR filed on [date]&#10;2. Action taken report&#10;3. Names of officers involved"
                    style={{ ...INPUT_STYLE, minHeight: 110, resize: 'none' }} />
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginBottom: 16 }}>
                  <div>
                    <label style={LABEL_STYLE}>Your Name</label>
                    <input value={form.applicantName} onChange={e => inp('applicantName', e.target.value)}
                      placeholder="Your full name" style={INPUT_STYLE} />
                  </div>
                  <div>
                    <label style={LABEL_STYLE}>Your Address</label>
                    <input value={form.applicantAddress} onChange={e => inp('applicantAddress', e.target.value)}
                      placeholder="Full address" style={INPUT_STYLE} />
                  </div>
                </div>

                <button onClick={handleGenerate} disabled={loading}
                  style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, width: '100%', padding: '13px 0', borderRadius: 11, background: `linear-gradient(135deg,${G},${GL})`, border: 'none', cursor: loading ? 'not-allowed' : 'pointer', color: '#0a0808', fontWeight: 700, fontSize: 14, opacity: loading ? 0.7 : 1 }}>
                  {loading ? <Loader2 size={15} style={{ animation: 'spin 0.8s linear infinite' }} /> : <FileQuestion size={15} />}
                  {loading ? 'Generating AI RTI Application...' : 'Generate RTI Application'}
                </button>
                <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
              </div>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div style={{ background: '#111120', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 14, padding: 22 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
                  <h3 style={{ fontFamily: 'Playfair Display,serif', fontSize: 17, color: G }}>✅ RTI Application Ready</h3>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button onClick={handleCopy}
                      style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 9, fontSize: 12, cursor: 'pointer', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', color: copied ? '#4ade80' : MUTED }}>
                      {copied ? <CheckCircle size={13} /> : <Copy size={13} />}
                      {copied ? 'Copied!' : 'Copy'}
                    </button>
                    <button onClick={handleDownloadPDF}
                      style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 9, fontSize: 12, cursor: 'pointer', background: `rgba(201,168,76,0.15)`, border: `1px solid ${G}`, color: G, fontWeight: 600 }}>
                      <Download size={13} /> Download PDF
                    </button>
                  </div>
                </div>
                <pre style={{ fontSize: 13, color: 'rgba(232,228,216,0.85)', whiteSpace: 'pre-wrap', fontFamily: 'DM Sans,sans-serif', lineHeight: 1.8, padding: 16, borderRadius: 11, background: '#0a0a0f', border: '1px solid rgba(42,42,62,1)', maxHeight: 420, overflowY: 'auto' }}>
                  {result.application}
                </pre>
              </div>

              <div style={{ background: 'rgba(74,222,128,0.05)', border: '1px solid rgba(74,222,128,0.2)', borderRadius: 12, padding: 16, fontSize: 13, color: 'rgba(232,228,216,0.8)', lineHeight: 1.7 }}>
                <p style={{ color: '#4ade80', fontWeight: 600, marginBottom: 8 }}>📌 Next Steps:</p>
                <p>1. Print and sign the application · 2. Attach ₹10 IPO or DD · 3. Submit to PIO or send by registered post · 4. Keep acknowledgement · 5. Response expected within <strong style={{ color: G }}>30 days</strong></p>
              </div>

              <button onClick={() => setResult(null)}
                style={{ padding: '10px 0', borderRadius: 11, background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', cursor: 'pointer', color: MUTED, fontSize: 13, width: '100%' }}>
                Generate Another RTI
              </button>
            </div>
          )}
        </div>
      )}

      {activeTab === 'guide' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div style={{ background: '#111120', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 14, padding: 22 }}>
            <h3 style={{ fontWeight: 600, marginBottom: 18, color: TEXT }}>How to File RTI — Step by Step</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {RTI_GUIDE_STEPS.map(step => (
                <div key={step.step} style={{ display: 'flex', gap: 14 }}>
                  <div style={{ width: 32, height: 32, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontWeight: 700, fontSize: 13, background: 'rgba(201,168,76,0.18)', color: G }}>
                    {step.step}
                  </div>
                  <div>
                    <h4 style={{ fontWeight: 600, fontSize: 14, color: G, marginBottom: 4 }}>{step.title}</h4>
                    <p style={{ fontSize: 13, color: 'rgba(232,228,216,0.8)', lineHeight: 1.65 }}>{step.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ background: 'rgba(232,92,92,0.05)', border: '1px solid rgba(232,92,92,0.25)', borderRadius: 12, padding: 18 }}>
            <h4 style={{ color: '#e85c5c', fontSize: 14, fontWeight: 600, marginBottom: 12 }}>⚠️ What Cannot be Asked Under RTI</h4>
            <ul style={{ margin: 0, paddingLeft: 16 }}>
              {RTI_EXEMPTIONS.map((ex, i) => (
                <li key={i} style={{ fontSize: 13, color: 'rgba(232,228,216,0.75)', marginBottom: 6, lineHeight: 1.5 }}>{ex}</li>
              ))}
            </ul>
          </div>

          <div style={{ background: 'rgba(129,140,248,0.06)', border: '1px solid rgba(129,140,248,0.2)', borderRadius: 12, padding: 16, fontSize: 13, color: 'rgba(232,228,216,0.8)', lineHeight: 1.7 }}>
            🌐 <strong style={{ color: '#818cf8' }}>Online Filing:</strong> File RTI online for Central Government at <strong style={{ color: G }}>rtionline.gov.in</strong> · No postal order needed · Get instant acknowledgement
          </div>
        </div>
      )}
    </div>
  );
}
